# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.box = "debian/bookworm64"
 config.vm.box_version = "12.20240212.1"
 config.vm.provider "virtualbox" do |vb|
 	vb.gui = true
    vb.memory = "8192"
    vb.name = "vm-arroyito"
 end
end
